# Generated by Django 2.2.6 on 2019-11-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBing', '0002_auto_20191101_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='response_count',
            new_name='respondant_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='most_three_response',
        ),
        migrations.RemoveField(
            model_name='item',
            name='response_count',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='date',
        ),
        migrations.AddField(
            model_name='response',
            name='respondant_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_end_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_start_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='upload_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
