# Generated by Django 2.2.6 on 2019-11-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBing', '0002_auto_20191122_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='multiple_choice',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='personal_data',
            field=models.BooleanField(null=True),
        ),
    ]
