# Generated by Django 2.2.6 on 2019-11-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBing', '0003_auto_20191103_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
