# Generated by Django 2.2.6 on 2019-12-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surBing', '0003_auto_20191204_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='similartiy1',
            new_name='similarity1',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='similartiy2',
            new_name='similarity2',
        ),
    ]
