# Generated by Django 2.2.6 on 2019-11-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBing', '0003_auto_20191124_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='selection',
            field=models.ManyToManyField(blank=True, to='surBing.Selection'),
        ),
    ]
