# Generated by Django 2.2.6 on 2019-11-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBing', '0004_auto_20191105_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='question_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
