# Generated by Django 2.2.6 on 2019-12-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surBing', '0004_auto_20191204_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='related_survey1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointed_mostly_related', to='surBing.Survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='related_survey2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointed_secondly_related', to='surBing.Survey'),
        ),
    ]
