# Generated by Django 2.2.4 on 2019-11-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surBing', '0006_auto_20191118_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='survey_ongoing',
        ),
    ]
