# Generated by Django 2.2.4 on 2019-11-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surBing', '0007_remove_cart_survey_ongoing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='survey_completed',
            new_name='survey',
        ),
    ]
