# Generated by Django 2.2.6 on 2019-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBing', '0008_auto_20191118_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_id', models.IntegerField()),
                ('selection', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='surveyongoing',
            old_name='target_personnel',
            new_name='target_respondant_count',
        ),
        migrations.AddField(
            model_name='surveyongoing',
            name='target_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='selection_list',
            field=models.ManyToManyField(to='surBing.Selection'),
        ),
    ]
